### ISSUE TITLE
[BUG] Workbunny\WebmanCoroutine\Events\SwooleEvent 在输出大的响应对象时，会出现响应对象长度不对的情况

### ISSUE THREAD

**Issue by tourze** [workbunny/webman-coroutine#12]
我现在使用workerman来做API，有一些js/css我也是通过php来输出的。使用默认的Select驱动是没问题的，但使用Workbunny\WebmanCoroutine\Events\SwooleEvent，会导致部分js/css输出不完整。
表现为输出的content-length是正确的，但是输出的内容长度小于content-length，导致浏览器一直在等待请求响应。

初步定位到是这里没触发
![image](https://github.com/user-attachments/assets/f1f340dc-45c0-48e8-8a83-aa6db52b4d54)

在应用侧，可以使用这样子的代码来强制输出
```
        while ($connection->getSendBufferQueueSize() > 0) {
            $connection->baseWrite();
        }
```

**Comment by tourze** [comment]
经测试，发现主要问题是在这里，https://github.com/workbunny/webman-coroutine/blob/260f67acc20092a37929a25375bc32000b3ec67e/src/Events/SwooleEvent.php#L114 这里总是返回false

**Comment by chaz6chez** [comment]
- 在alpine、Ubuntu等linux系统环境下构建的swoole未能复现该问题
- 在mac系统下以相同拓展构建的swoole存在该问题

# 问题描述

通过Event::isset判断write事件为false，但Event::add时报事件already 

**该问题暂时挂起，等待修复方案，该问题暂未波及常用生产环境**

**Comment by chaz6chez** [comment]
该问题最小复现样例：

[issue-12.zip](https://github.com/user-attachments/files/17341422/issue-12.zip)

- 执行composer安装
- 执行php -d extension=swoole index.php start
- 请求站点

**Comment by NathanFreeman** [comment]
swoole在`Swoole\Event`这块的文档还是不够详细，还得补充一下文档关于这里的使用场景。大概这样修复一下就行了

**Comment by tourze** [comment]
https://github.com/workbunny/webman-coroutine/tree/ac9e56370063caf9e702df389e761c11bc0acc10 这个版本，测试可以解决本issue，已在 macos / php8.3.12 / swoole 5.1.4 测试
