### ISSUE TITLE
[RFC]监听类进程、CoroutineWebServer的平滑重启/关闭

### ISSUE THREAD

**Issue by chaz6chez** [workbunny/webman-coroutine#23]
### 1. 描述

workerman/webman在重启或关闭的时候可能存在连接依然在执行业务逻辑消费，新链接依然在接收on Message回调，为了尽可能较为平滑和避免一些异常，建议实现在on Worker Stop中加入对协程消费者的的消费等待，on Message的waitFor处加入connection的pause直到等待结束恢复；

有配置选择开启/关闭，默认关闭，兼容旧版

### 2. 场景

监听类Worker的重启和关闭

### 3. 期望版本

- webman-coroutine 版本: 1.3
- 协程环境下的驱动: all

### 4. 兼容信息

无

**Comment by Tinywan** [comment]
这个不能使用现有的workerman的平滑重启/关闭机制吗？

**Comment by chaz6chez** [comment]
> 这个不能使用现有的workerman的平滑重启/关闭机制吗？

Webman貌似没有暂停连接的接受，原因是之前的处理是没有协程的，不会出让当前控制权，阻塞业务会执行完毕才会归还控制权到eventloop，stop的时候根据stop timeout来进行worker的kill；先在增加了协程以后，onMessage的协程消费者遇到阻塞会出让控制权，但业务逻辑可能并没有执行完毕，控制权会更早的交还给stop
