### ISSUE TITLE
[QUESTION] 关于CoroutineWebServer类的继承问题

### ISSUE THREAD

**Issue by luoyue712** [workbunny/webman-coroutine#29]
### 问题描述

在webman^1.6环境下更改了process目录，由Webman\App更改到了app\process\Http，是否可以更改CoroutineWebServer类的继承。

**Comment by chaz6chez** [comment]
兼容1.6，app\process\Http只是Webman\App的其中一种实现方式而已，app\process\Http与CoroutineWebServer是平级关系

**Comment by luoyue712** [comment]
我在app\process\Http上做了修改，但是我想让CoroutineWebServer继承这个实现自己的逻辑

**Comment by chaz6chez** [comment]
> 我在app\process\Http上做了修改，但是我想让CoroutineWebServer继承这个实现自己的逻辑

你的process\Http启动的时候可以指定workerClass为Workbunny\WebmanCoroutine\Utils\Worker\Server，在config/process.php中添加修改，即可实现app\process\Http的协程化，这样就无需开启CoroutineWebServer进程了
